import turtle
sc=turtle.Screen()
sc.bgcolor("green")
sc.setup(500,500)
pointer=turtle.Turtle()
pointer.color("blue")
pointer.forward(200)
pointer.left(90)
pointer.forward(100)
pointer.left(90)
pointer.forward(200)
pointer.left(90)
pointer.forward(100)
turtle.done()
