my_tuple=()
print("my_tuple")
my_tuple=(1,2,3,4,5)
print(my_tuple)
my_tuple=(1,"hello",3.4)
print(my_tuple)
my_tuple=("mouse",[1,2,3],(4,5,6))
print(my_tuple)
my_tuple=('p','e','n','t','a','g','o','n')
print(my_tuple[0])
print(my_tuple[1])
print(my_tuple[2])
n_tuple=('mouse',[1,2,3],(4,5,6))
print(n_tuple[0][3])
print(n_tuple[1][1])
print("Sliced_tuple:",my_tuple[1:3])
for letter in my_tuple:
    print("Hello",letter)

